apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collabora
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry.gitlab.collabora.com
    chart: productivity/cool-controller-registry/helm-charts/collabora-online-umbrella
    targetRevision: 1.1.9
    helm:
      valueFiles:
        - values.yaml
      releaseName: collabora
  destination:
    server: https://kubernetes.default.svc
    namespace: collabora
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
